"""create initial schema

Revision ID: 6ac50fb82673
Revises: 
Create Date: 2026-09-02 00:47:20.254364+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '6ac50fb82673'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema changes of this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', postgresql.CITEXT(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies')),
    sa.UniqueConstraint('slug', name=op.f('uq_companies_slug')),
    sa.UniqueConstraint('stripe_customer_id', name=op.f('uq_companies_stripe_customer_id'))
    )
    op.create_table('subscriptions',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('plan', sa.Enum('starter', 'professional', 'enterprise', name='subscription_plan'), nullable=False),
    sa.Column('status', sa.Enum('trialing', 'active', 'past_due', 'canceled', name='subscription_status'), nullable=False),
    sa.Column('monthly_cv_quota', sa.Integer(), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('monthly_cv_quota >= 0', name=op.f('ck_subscriptions_monthly_cv_quota_non_negative')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_subscriptions_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions')),
    sa.UniqueConstraint('company_id', name=op.f('uq_subscriptions_company_id')),
    sa.UniqueConstraint('stripe_subscription_id', name=op.f('uq_subscriptions_stripe_subscription_id'))
    )
    op.create_table('usage_records',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('cv_processed_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cv_processed_count >= 0', name=op.f('ck_usage_records_cv_processed_count_non_negative')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_usage_records_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_records')),
    sa.UniqueConstraint('company_id', 'period_start', name=op.f('uq_usage_records_company_id_period_start'))
    )
    op.create_index(op.f('ix_usage_records_company_id'), 'usage_records', ['company_id'], unique=False)
    op.create_table('users',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'recruiter', 'viewer', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_users_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.create_table('webhooks',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('event_type', sa.Enum('candidate.high_match', 'candidate.stage_changed', name='webhook_event_type'), nullable=False),
    sa.Column('secret', sa.String(length=255), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('threshold IS NULL OR threshold BETWEEN 0 AND 100', name=op.f('ck_webhooks_threshold_within_range')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_webhooks_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhooks'))
    )
    op.create_index(op.f('ix_webhooks_company_id'), 'webhooks', ['company_id'], unique=False)
    op.create_table('jobs',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('required_skills', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('min_years_experience', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'USD'"), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('remote_allowed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('status', sa.Enum('open', 'closed', 'archived', name='job_status'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('min_years_experience >= 0', name=op.f('ck_jobs_min_years_experience_non_negative')),
    sa.CheckConstraint('salary_min IS NULL OR salary_max IS NULL OR salary_min <= salary_max', name=op.f('ck_jobs_salary_range_ordered')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_jobs_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_jobs_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index(op.f('ix_jobs_company_id'), 'jobs', ['company_id'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('webhook_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('delivered', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('attempts >= 0', name=op.f('ck_webhook_deliveries_attempts_non_negative')),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhooks.id'], name=op.f('fk_webhook_deliveries_webhook_id_webhooks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_deliveries'))
    )
    op.create_index(op.f('ix_webhook_deliveries_webhook_id'), 'webhook_deliveries', ['webhook_id'], unique=False)
    op.create_table('candidates',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('parse_status', sa.Enum('pending', 'processing', 'completed', 'failed', name='parse_status'), nullable=False),
    sa.Column('stage', sa.Enum('screening', 'interview', 'offer', 'hired', 'rejected', name='candidate_stage'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_candidates_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_candidates_job_id_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_candidates_uploaded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidates')),
    sa.UniqueConstraint('company_id', 'file_hash', name=op.f('uq_candidates_company_id_file_hash'))
    )
    op.create_index(op.f('ix_candidates_company_id'), 'candidates', ['company_id'], unique=False)
    op.create_table('candidate_profiles',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('years_experience', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('education', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('work_history', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('expected_salary', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('parsed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('years_experience IS NULL OR years_experience >= 0', name=op.f('ck_candidate_profiles_years_experience_non_negative')),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_candidate_profiles_candidate_id_candidates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_profiles')),
    sa.UniqueConstraint('candidate_id', name=op.f('uq_candidate_profiles_candidate_id'))
    )
    op.create_table('match_scores',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('skill_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('experience_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('salary_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('location_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('breakdown', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('experience_score BETWEEN 0 AND 100', name=op.f('ck_match_scores_experience_score_within_range')),
    sa.CheckConstraint('location_score BETWEEN 0 AND 100', name=op.f('ck_match_scores_location_score_within_range')),
    sa.CheckConstraint('overall_score BETWEEN 0 AND 100', name=op.f('ck_match_scores_overall_score_within_range')),
    sa.CheckConstraint('salary_score BETWEEN 0 AND 100', name=op.f('ck_match_scores_salary_score_within_range')),
    sa.CheckConstraint('skill_score BETWEEN 0 AND 100', name=op.f('ck_match_scores_skill_score_within_range')),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_match_scores_candidate_id_candidates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_match_scores_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_scores')),
    sa.UniqueConstraint('candidate_id', 'job_id', name=op.f('uq_match_scores_candidate_id_job_id'))
    )
    op.create_index(op.f('ix_match_scores_job_id'), 'match_scores', ['job_id'], unique=False)
    op.create_table('notes',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_notes_author_id_users')),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_notes_candidate_id_candidates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notes'))
    )
    op.create_index(op.f('ix_notes_candidate_id'), 'notes', ['candidate_id'], unique=False)
    op.create_table('stage_transitions',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=False),
    sa.Column('from_stage', sa.Enum('screening', 'interview', 'offer', 'hired', 'rejected', name='candidate_stage'), nullable=True),
    sa.Column('to_stage', sa.Enum('screening', 'interview', 'offer', 'hired', 'rejected', name='candidate_stage'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('from_stage IS DISTINCT FROM to_stage', name=op.f('ck_stage_transitions_stage_actually_changed')),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_stage_transitions_candidate_id_candidates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name=op.f('fk_stage_transitions_changed_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stage_transitions'))
    )
    op.create_index(op.f('ix_stage_transitions_candidate_id'), 'stage_transitions', ['candidate_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the schema changes of this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stage_transitions_candidate_id'), table_name='stage_transitions')
    op.drop_table('stage_transitions')
    op.drop_index(op.f('ix_notes_candidate_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_match_scores_job_id'), table_name='match_scores')
    op.drop_table('match_scores')
    op.drop_table('candidate_profiles')
    op.drop_index(op.f('ix_candidates_company_id'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_webhook_deliveries_webhook_id'), table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('ix_jobs_company_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_webhooks_company_id'), table_name='webhooks')
    op.drop_table('webhooks')
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_usage_records_company_id'), table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_table('subscriptions')
    op.drop_table('companies')
    # ### end Alembic commands ###
